### ISSUE TITLE
decouple from gulp

### ISSUE THREAD

**Issue by juliangruber** [Jaguard/time-require#4]
it would be sweet to be able to run

``` bash
$ time-require
```

without having gulp installed, none of my projects use gulp but this tool looks nevertheless useful

**Comment by yields** [comment]
+500 !

**Comment by cyparu** [comment]
`time-require` does not depend on [gulpjs](http://gulpjs.com) but aside of using it as a build infrastructure, also nicely fit with it (and BTW any other [Liftoff](https://github.com/tkellen/node-liftoff) based **CLI** tools) using the Liftoff's `--require` preload support. For this specific purpose I also created [gulpt](https://github.com/jaguard/gulpt), a `gulp` CLI wrapper that automatically preload `time-require`. These things are already clarified under [time-require's usage](https://github.com/jaguard/time-require#usage).

For a simple embedding into your own app(s) just simply add `require("time-require");` as a first line (to pick all subsequent `require()` as well) into your main module so once the app is closed you'll get the nice charts. The actual configuration ( `--verbose` (or `--V`)  or/and `--sorted` (or `--s`))  will be picked from the running CLI.
