### ISSUE TITLE
question: what time is measured?

### ISSUE THREAD

**Issue by junosuarez** [Jaguard/time-require#5]
is this measuring the synchronous time of the actual `require()` calls to load modules, or is it instrumenting and measuring execution time for functions inside those modules and then reporting grouped by module?

**Comment by cyparu** [comment]
The `time-require` module actually hook the `require()` mechanism so the time measured is the **_synchronous**_ required module initialization (basically the module factory).
The original intent for this module was to visually track the **slooow** dependencies / modules and to postpone and/or [laazy](https://github.com/jaguard/laazy) require them on-demand.
